stages:
  - build-firmware

variables:
    GIT_SUBMODULE_STRATEGY: normal

build:
  stage: build-firmware
  tags:
    - has3
  script:
    - $env:PATH = "$($env:PYTHON_WAF);$env:PATH"
    - cd "$CI_PROJECT_DIR\HAS3_Firmware\HAS3"
    - waf.bat distclean
    - waf.bat --conditions=debug configure build
