name: C Project CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Check GCC
        run: gcc --version

      - name: Build Project
        run: mingw32-make
          

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
