def build(bld):

    toolchain = bld.env["UsedToolchain"]
    if not toolchain:
        bld.fatal('Environment parameter "UsedToolchain" is not available! Make sure to provide the environment parameter "UsedToolchain" in the root wscript file of your project. e.g.: conf.env["UsedToolchain"] = "gccarmemb"')
    
    platform  = bld.env["UsedPlatform"]
    if not platform:
        bld.fatal('Environment parameter "UsedPlatform" is not available! Make sure to provide the environment parameter "UsedPlatform" in the root wscript file of your project. e.g.: conf.env["UsedPlatform"]  = "netx90"')
    
    comp_prefix = bld.get_name_prefix(
        toolchain = toolchain,
        platform  = platform)
    
    path = './../../../External/netx/cifXToolkit/'
        
# Component cifXToolkit --------------------------------------------------------------------
    sources  = [
        path + "Source/cifXDownload.c",
        path + "Source/cifXEndianess.c",
        path + "Source/cifXFunctions.c",
        path + "Source/cifXHWFunctions.c",
        path + "Source/cifXInit.c",
        path + "Source/cifXInterrupt.c",
        path + "Source/Hilmd5.c",
        path + "Source/netX90_netX4x00.c",
        path + "Source/netX5x_hboot.c",
        path + "Source/netX5xx_hboot.c",
        path + "OSAbstraction/OS_Custom.c",
        path + "User/TKitUser_Custom.c",
        ]
    
    sources_spm  = [
        path + "SerialDPM/SerialDPMInterface.c",
        ]
    
    
    includes = [
        path + "OSAbstraction",
        path + "SerialDPM",
        path + "Source",
        path + "Common/cifXAPI/includes",
        path + "Common/HilscherDefinitions",
        ]
    
    uses = [
            comp_prefix + "netx_drv",
           ]
    
    bld.stlib(
        target          = "cifXToolkit",
        name            = comp_prefix + "cifXToolkit",
        description     = "Parallel DPM cifXToolkit Library for netX",
        displaygroup    = "Libraries",
        platform        = platform,
        toolchain       = toolchain,
        use              = uses,
        source          = sources,
        includes        = includes,
        export_includes = includes,
        )
        
    bld.stlib(
        target          = "cifXToolkit_spm",
        name            = comp_prefix + "cifXToolkit_spm",
        description     = "Serial DPM (SPM) cifXToolkit Library for netX",
        displaygroup    = "Libraries",
        platform        = platform,
        toolchain       = toolchain, 
        use              = uses,
        source          = sources + sources_spm,
        includes        = includes,
        defines         = ["CIFX_TOOLKIT_HWIF"],
        export_includes = includes,
        export_defines  = ["CIFX_TOOLKIT_HWIF"],
        )
    
    bld.sdkcomponent(
        name            = "cifXToolkit_sdk",
        export_includes = includes,
        )