stages:
  - setup
  - test

variables:
    WORKSPACE_PATH: "$CI_PROJECT_DIR"
    GIT_SUBMODULE_STRATEGY: normal


setup_job:
  stage: setup
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2

  script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - echo "SETUP SUCCESS!!!"
  only:
    - main
    - merge_requests


test_job:
  stage: test
  image: registry.gitlab.com/dematic/pd-scs/lib/netx/cpputest-ci:latest
  script:
    - echo "Running tests..."
    - cd "$WORKSPACE_PATH/netx90_ddrv/tests/_build/gnu_make"
    - make WORKSPACE_PATH="$WORKSPACE_PATH" clean
    - make WORKSPACE_PATH="$WORKSPACE_PATH"
  only:
    - main
    - merge_requests
