name: SonarQube Cloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Cloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@c7ee0f9df90b7aa20e8dcf9695dcfe2e7da5b4f2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
